## 전체 흐름
# 1. Github repository의 코드를 가져온다.
# 2. Node.js를 Github actions 서버에 설치한다.
# 3. 의존성 라이브러리를 설치한다.
# 4. 테스트를 실행한다.

name: Github Actions로 테스트 자동화하기
on:
  push:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 의존성(라이브러리) 설치
        run: npm ci

      - name: 테스트 실행하기
        run: npm run test
